---
- name: Generate the index.html file
  ansible.builtin.template:
    src: index.html.j2
    dest: /home/ubuntu/index.html

- name: Run the httpd image as a container
  ansible.builtin.docker_container:
    name: "{{ hote_name }}"
    image: "httpd:{{ image_version }}"
    state: started
    ports:
      - "{{PORT_ex}}:{{PORT_in}}"
    volumes:
      - /home/ubuntu/index.html:/usr/local/apache2/htdocs/index.html

- name: Install git & wget
  ansible.builtin.apt:
    name: '{{item}}'
    state: present
    loop:
      - git
      - wget
  when: ansible_distribution == "{{ ansible_user }}"
